import type { CharacterConfig } from "./characterPresets";

export {
  CHARACTER_BOTTOM_COLORS,
  CHARACTER_EXPRESSIONS,
  CHARACTER_FACE_SHAPES,
  CHARACTER_GENDERS,
  CHARACTER_HAIR_COLORS,
  CHARACTER_HAIR_STYLES,
  CHARACTER_INSTRUMENTS,
  CHARACTER_TOP_COLORS,
  CHARACTER_TOP_STYLES,
  DEFAULT_CHARACTER_CONFIG,
  getCharacterConfig,
  getCharacterBottomColorLabel,
  getCharacterExpressionLabel,
  getCharacterFaceShapeLabel,
  getCharacterGenderLabel,
  getCharacterHairColorLabel,
  getCharacterHairStyleLabel,
  getCharacterInstrumentLabel,
  getCharacterLayers,
  getCharacterSummary,
  getCharacterTopColorLabel,
  getCharacterTopStyleLabel,
  getDefaultCharacterConfig,
  isCharacterBottomColor,
  isCharacterExpression,
  isCharacterFaceShape,
  isCharacterGender,
  isCharacterHairColor,
  isCharacterHairStyle,
  isCharacterInstrument,
  isCharacterTopColor,
  isCharacterTopStyle,
  normalizeCharacterConfig,
  resolveCharacterImageUrl,
  type CharacterBottomColor,
  type CharacterConfig,
  type CharacterExpression,
  type CharacterFaceShape,
  type CharacterGender,
  type CharacterHairColor,
  type CharacterHairStyle,
  type CharacterInstrument,
  type CharacterLayer,
  type CharacterLayerKey,
  type CharacterTopColor,
  type CharacterTopStyle,
} from "./characterPresets";

export type StageCharacterConfig = CharacterConfig;
